language: node_js

node_js:
  - lts/*

env:
  - TRAVIS_REPO_SLUG = LifeDrainFrog/x86_ref_book_web

script:
  - npm run build

after success:
  - ./scripts/delpy.sh

cache:
  yarn: true
  directories:
  - node_modules
