language: node_js

node_js:
  - lts/*

env:
  - TRAVIS_REPO_SLUG = LifeDrainFrog/x86_ref_book_web

script:
  - npm run build

after_success:
  - bash ./scripts/deploy.sh

cache:
  yarn: true
  directories:
  - node_modules
