language: node_js

node_js:
  - lts/*

env:
  global:
    - GITHUB_REPO: "LifeDrainFrog/x86_ref_book_web"

script:
  - npm run build

after_success:
  - bash ./scripts/deploy.sh

cache:
  npm: true
  directories:
  - node_modules


