language: node_js

node_js:
  - lts/*

env:
  global:
    - GITHUB_REPO: "tizee/x86_ref_book_web"

script:
  - npm install
  - npm run build

after_success:
  - bash ./scripts/deploy.sh

cached:
  npm: true
  directories: 
   - node_modules

